language: node_js
node_js:
  - "node"
  - "10"

before_script:
  - npm i -g verdaccio@4.6.2
  - verdaccio &
  - sleep 1
  - npx npm-cli-adduser@1.1.4 --registry $NPM_REGISTRY_URL --username $NPM_USERNAME --password $NPM_PASSWORD --email $NPM_EMAIL --scope $NPM_SCOPE

script:
  - npm test
  - npm run lint
  - npm run build
  - npm publish --dry-run
  - npm whoami --registry $NPM_REGISTRY_URL
  - |
    sed -i -r "s/\"name\": \"sol-merger\"/\"name\": \"@$NPM_SCOPE\/sol-merger\"/" package.json
  - npm publish --registry $NPM_REGISTRY_URL
  - npm i -g "@$NPM_SCOPE/sol-merger@latest" --registry $NPM_REGISTRY_URL
  - bash ./test-cli.sh
