# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    env:
      NPM_REGISTRY_URL: http://localhost:4873
      NPM_USERNAME: admin
      NPM_PASSWORD: admin
      NPM_EMAIL: admin@example.com
      NPM_SCOPE: test-org

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run lint
    - run: npm publish --dry-run
    # run verdaccio and setup user
    - run: ./node_modules/.bin/verdaccio &
    - run: sleep 1
    - run: ./node_modules/.bin/npm-cli-adduser --registry $NPM_REGISTRY_URL --username $NPM_USERNAME --password $NPM_PASSWORD --email $NPM_EMAIL --scope $NPM_SCOPE
    # update
    - run: npm whoami --registry $NPM_REGISTRY_URL
    - run: |
        sed -i -r "s/\"name\": \"sol-merger\"/\"name\": \"@$NPM_SCOPE\/sol-merger\"/" package.json
    - run: npm publish --registry $NPM_REGISTRY_URL
    # install and run tests
    - run: npm i -g "@$NPM_SCOPE/sol-merger@latest" --registry $NPM_REGISTRY_URL
    - run: /bin/bash ./test-cli.sh
